[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/generated/partners/*.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"

[[headers]]
  for = "/generated/partners/logos/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
